export const RESOURCES_BUY_PULP = 'RESOURCES_BUY_PULP';
export const RESOURCES_MAKE_PAPER = 'RESOURCES_MAKE_PAPER';
export const RESOURCES_SELL_PAPER = 'RESOURCES_SELL_PAPER';
export const RESOURCES_PAPER_PRICE_INCREASE = 'RESOURCES_PAPER_PRICE_INCREASE';
export const RESOURCES_PAPER_PRICE_DECREASE = 'RESOURCES_PAPER_PRICE_DECREASE';
export const DEMAND_UPDATE = 'DEMAND_UPDATE';
export const DEMAND_SLOPE_UPDATE = 'DEMAND_SLOPE_UPDATE';
export const DEMAND_BUY_FACTOR_UPDATE = 'DEMAND_SLOPE_UPDATE';
